version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend/node_modules:/app/node_modules
    volumes:
      - ./frontend:/app  # ✅ 只挂载代码
      - /app/node_modules  # ✅ 让 node_modules 继续使用容器里的

    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: access_monitor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: access_monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitorpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
